### ISSUE TITLE
How to change the language to Chinese

### ISSUE THREAD

**Issue by chenxiagua** [TraderSamwise/tealstreet_beta#2]
I add code in y18n var y18n = new Y18N({
   directory: './locales',
   locale: 'zh'
});
doesn't work. At the same time, it is also necessary to modify the trading view to a Chinese interface

**Comment by TraderSamwise** [comment]
@chenxiagua its going to take us a bit more time to get language support working. If you want to help with Chinese though let me know and I can reach out once we are ready to start working on it properly
